### ISSUE TITLE
"TypeError: argument of type 'NoneType' is not iterable" in nessusToExcel.py

### ISSUE THREAD

**Issue by rm1984** [spyr0-sec/helper-scripts#1]
Hi,
I'm trying your helper script on a .nessus XML file from Nessus Professional 10.0.2.
This is what I get:

`Traceback (most recent call last):
  File "/tmp/NEFFUF/nessusToExcel.py", line 1348, in <module>
    extractAll()
  File "/tmp/NEFFUF/nessusToExcel.py", line 38, in extractAll
    extractHosts()
  File "/tmp/NEFFUF/nessusToExcel.py", line 73, in extractHosts
    report_host_os = nfr.host.detected_os(report_host)
  File "/usr/local/lib/python3.10/dist-packages/nessus_file_reader/host/host.py", line 119, in detected_os
    if "&quot;" in operating_system:
TypeError: argument of type 'NoneType' is not iterable`

The issue seems to be in the "hosts" module.
Thank you!

**Comment by spyr0-sec** [comment]
Unfortunately this is a known issue with nessus_file_reader - https://github.com/LimberDuck/nessus-file-reader/issues/8

Their recommendation is to downgrade the pip module
```
pip uninstall nessus_file_reader
pip install nessus_file_reader==0.3.0
```
